### ISSUE TITLE
[BUG] Extension simply doesn't work

### ISSUE THREAD

**Issue by DalekCraft2** [vshaxe/vscode-checkstyle#18]
I'm not sure what information to provide, so I'll just describe the problem for now:
I have the extension installed with the other Haxe extensions, but it stopped detecting problems a while ago, and I can't figure out what the issue is. I've tried clearing the VS Code editor history, and I've tried disabling every non--Haxe-related extension, but it still does nothing. Maybe it is using an outdated checkstyle version, or it isn't compatible with newer VS Code releases.

**Comment by AlexHaxe** [comment]
I've just released an updated version that should be compatible with latest vshaxe releases (> 2.24.x). 

also includes "new" CommentOutCode check
