### ISSUE TITLE
Default configuration

### ISSUE THREAD

**Issue by Simn** [vshaxe/vscode-checkstyle#3]
Currently it's a bit awkward: By default we show warnings for everything, then when generating a default configuration pretty much all warnings disappear.

It would be nice to have a more sensible default config that performs some basic checks but doesn't complain about too much nonsense.

**Comment by ibilon** [comment]
haxe-checkstyle has a default configuration file https://github.com/HaxeCheckstyle/haxe-checkstyle/blob/dev/checkstyle.json how it compares to activating all the checks.

**Comment by Simn** [comment]
But that's not the default configuration it generates when using `--default-config`, right?

**Comment by ibilon** [comment]
No, it's the one used when you run it through haxelib.

**Comment by Simn** [comment]
I see, but that doesn't really help us much.

**Comment by ibilon** [comment]
Maybe we could use that one instead of calling `addAllChecks()`.

**Comment by Simn** [comment]
Yes that might make sense.

It's just strange that you cannot refine the default config by generating and modifying it. Instead you get that completely different config. But that's probably more of a haxe-checkstyle problem.

**Comment by ibilon** [comment]
Well it's only supposed to use that "default" if it can't find that file,
so half haxe-checstyle half us.

**Comment by Simn** [comment]
This is somewhat important, at the moment the extension can't just be used on a new project without being a huge nuisance.

**Comment by ibilon** [comment]
Looked more into this, the file I linked isn't the default config, it's just the one they use.

So It's back to your original message we need "to have a more sensible default config".
