### ISSUE TITLE
Is this still alive?

### ISSUE THREAD

**Issue by 3vilguy** [vshaxe/vscode-checkstyle#4]
Hello there @Simn.
I was just wondering if you guys ever made it to VS Studio marketplace. I can't find it in there but I'd love to see checkstyle integrated with it.

**Comment by Simn** [comment]
I have no idea... Does it still work? :)

**Comment by 3vilguy** [comment]
I dunno :) How can I install it if it's not in the marketplace?

**Comment by ibilon** [comment]
* Go to vscode's extensions folder (C:\Users\<username>\.vscode\extensions on Windows, ~/.vscode/extensions otherwise).
* Clone the repository
* Do `haxe build.hxml`

Now if you launch vscode it should be an active extension

**Comment by 3vilguy** [comment]
Thanks @ibilon, I did like you said and it seems to be working :)

One small thing tho, while doing `haxe build.hxml` I got:
```
src/Main.hx:32: characters 48-73 : Warning : Use [`workspaceFolders`](#workspace.workspaceFolders) instead.
```

Soooo, any reason why you never made it to VS Studio marketplace? Maybe that would attract more contributors.

**Comment by Gama11** [comment]
@AlexHaxe has been doing a lot of great work on this extension (and also checkstyle itself) lately, so I think we're not too far from making an actual release. :) I guess we first need to at least update the readme though and include some "getting started"-type info there.
