### ISSUE TITLE
Limit checkstyle run to files from source folder

### ISSUE THREAD

**Issue by AlexHaxe** [vshaxe/vscode-checkstyle#8]
vscode-checkstyle runs when you open a file, regardless where that file comes from. If you use `F12` / `Goto definition` you can land in a file from a Haxe library which might adhere to a different coding style. 
Reporting checkstyle messages for files outside of a predefined set of folders should be disabled.

Most people probably use only one source folder per project, but some might have a few, so there should be an option to configure an array of source paths to feed to checkstyle.

**Comment by Gama11** [comment]
Vshaxe has a setting called `haxe.diagnosticsPathFilter` that sounds quite similar to this.
